try {
    let a 
    console.log(a.length);
    console.log("form inside");
} catch (e) {
    console.log("inside catch");
}
console.log("outside trycatch block");

// hi there 

// by putting a code block in a trycatch block. It ensures that if the code block throw an error, 
// The control will catch the error and will continue to execute rest of the code in the thread

